Model:
  # model parameter
  name: "vae"
  dataset: "rubber"
  distribution: "Bern"
  hidden_dims: [500, 200]
  latent_dim: 50
  input_channel: 784
  # train parameter
  batch_size: 100
  num_epochs: 200
  learning_rate: 0.0001
